Script started on 2015年03月16日 (週一) 11時30分53秒
]0;F74036019@2015cpp: ~/lab1F74036019@2015cpp:~/lab1$ whoami;pwd
F74036019
/home/F74036019/lab1
]0;F74036019@2015cpp: ~/lab1F74036019@2015cpp:~/lab1$ git config -l
user.name=Sean1127
user.email=wannaplay1304@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=http://github.com/Sean1127/lab1.git
branch.master.remote=notebook
branch.master.merge=refs/heads/master
remote.pc.url=http://github.com/Sean1127/lab1.git
remote.pc.fetch=+refs/heads/*:refs/remotes/pc/*
remote.notebook.url=https://github.com/Sean1127/lab1.git
remote.notebook.fetch=+refs/heads/*:refs/remotes/notebook/*
]0;F74036019@2015cpp: ~/lab1F74036019@2015cpp:~/lab1$ git clone https://github.com/Sean1127/lab1 .git
Cloning into 'lab1'...
remote: Counting objects: 19, done.[K
remote: Compressing objects:   6% (1/16)   [Kremote: Compressing objects:  12% (2/16)   [Kremote: Compressing objects:  18% (3/16)   [Kremote: Compressing objects:  25% (4/16)   [Kremote: Compressing objects:  31% (5/16)   [Kremote: Compressing objects:  37% (6/16)   [Kremote: Compressing objects:  43% (7/16)   [Kremote: Compressing objects:  50% (8/16)   [Kremote: Compressing objects:  56% (9/16)   [Kremote: Compressing objects:  62% (10/16)   [Kremote: Compressing objects:  68% (11/16)   [Kremote: Compressing objects:  75% (12/16)   [Kremote: Compressing objects:  81% (13/16)   [Kremote: Compressing objects:  87% (14/16)   [Kremote: Compressing objects:  93% (15/16)   [Kremote: Compressing objects: 100% (16/16)   [Kremote: Compressing objects: 100% (16/16), done.[K
remote: Total 19 (delta 2), reused 9 (delta 1), pack-reused 0[K
Unpacking objects:   5% (1/19)   Unpacking objects:  10% (2/19)   Unpacking objects:  15% (3/19)   Unpacking objects:  21% (4/19)   Unpacking objects:  26% (5/19)   Unpacking objects:  31% (6/19)   Unpacking objects:  36% (7/19)   Unpacking objects:  42% (8/19)   Unpacking objects:  47% (9/19)   Unpacking objects:  52% (10/19)   Unpacking objects:  57% (11/19)   Unpacking objects:  63% (12/19)   Unpacking objects:  68% (13/19)   Unpacking objects:  73% (14/19)   Unpacking objects:  78% (15/19)   Unpacking objects:  84% (16/19)   Unpacking objects:  89% (17/19)   Unpacking objects:  94% (18/19)   Unpacking objects: 100% (19/19)   Unpacking objects: 100% (19/19), done.
]0;F74036019@2015cpp: ~/lab1F74036019@2015cpp:~/lab1$ exit

Script done on 2015年03月16日 (週一) 11時31分54秒
